### ISSUE TITLE
Have you ever had any issues with the xepersian package?

### ISSUE THREAD

**Issue by ghost** [shahryareiv/asciimint-latex#1]
Hi

If you ever happen to have any question, then please open an issue at [the `xepersian` package issue tracker](https://github.com/persiantex/xepersian/issues) and I will be very happy to help out.

Best wishes, Vafa Khalighi (the author of the `xepersian` package)

**Comment by shahryareiv** [comment]
Thanks a lot @vafakhalighi ! Asciimint is a toolchain for converting Asciidoc documents to other publishable formats in some predefined styles. I created it for my personal publishing needs, and it (Asciimint-Latex) uses  `bidi` and `xepersian` for Persian PDF outputs. I will update xepersian package issue tracker, if encounter any issue.
Kind Regards
Shahryar
